[package]
name = "h2o"
version = "1.0.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]

[dependencies]
docopt = "0.8"
docopt_macros = "0.8"
serde = "1.0"
serde_derive = "1.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"

[profile.release]
lto = true
